### ISSUE TITLE
simple example doesn't work?

### ISSUE THREAD

**Issue by groovecoder** [projectfluent/fluent-web#2]
After I clone the repo, I tried `make build` and got:
```bash
/Users/lcrouch/code/projectfluent/fluent-web/src/index.js → fluent-web.js...
[!] Error: Could not resolve '../../fluent.js/fluent-dom/src/index' from src/index.js
Error: Could not resolve '../../fluent.js/fluent-dom/src/index' from src/index.js
    at error (/Users/lcrouch/code/projectfluent/fluent-web/node_modules/rollup/dist/rollup.js:3461:30)
    at /Users/lcrouch/code/projectfluent/fluent-web/node_modules/rollup/dist/rollup.js:21860:25
    at <anonymous>

make: *** [fluent-web.js] Error 1
```

I did `git clone git@github.com:projectfluent/fluent.js.git` alongside `fluent-web` and was able to get:
```bash
/Users/lcrouch/code/projectfluent/fluent-web/src/index.js → fluent-web.js...
(!) Unresolved dependencies
https://github.com/rollup/rollup/wiki/Troubleshooting#treating-module-as-external-dependency
cached-iterable (imported by ../fluent.js/fluent-dom/src/localization.js)
(!) Circular dependency: node_modules/fluent-langneg/src/locale.js -> node_modules/fluent-langneg/src/subtags.js -> node_modules/fluent-langneg/src/locale.js
created fluent-web.js in 168ms
 ✓ fluent-web.js built
```

But when I `open examples/simple.html` I see this error in the console:
```
SyntaxError: import declarations may only appear at top level of a module fluent-web.js:2 
```

**Comment by zbraniecki** [comment]
Hi @groovecoder - I landed #1 and tried to clone fresh and it seems that the examples work for me in Firefox. Can you confirm?

**Comment by zbraniecki** [comment]
@groovecoder - I've tested this again using Firefox and Chrome and all seems to work in the example. Can you verify pls?

**Comment by zbraniecki** [comment]
closing as per #6
